### PR TITLE
Split GB-GK into Light & Dark, redo build system to accommodate

### PR DESCRIPTION
**Pull request by sowelipililimute**

### CODE REVIEW

**Comment by m4u9** [comment]
@ochosi @bluesabre is this something that could benefit the upstream greybird theme as well?

**Comment by ochosi** [comment]
@Mau-G It could benefit Greybird, but I wouldn't like the added maintenance.

**Comment by m4u9** [comment]
> @Mau-G It could benefit Greybird, but I wouldn't like the added maintenance.

I'm willing to accept the merge because we have people asking for a dark theme, as long as porting the commits between Greybird <--> Greybird Geeko is doable and not overly complicated.

**Comment by sowelipililimute** [comment]
> > @Mau-G It could benefit Greybird, but I wouldn't like the added maintenance.
> 
> I'm willing to accept the merge because we have people asking for a dark theme, as long as porting the commits between Greybird <--> Greybird Geeko is doable and not overly complicated.

It'll be relatively easy. All you need to do is to copy over the modified upstream files to both light and dark without removing any downstream changes. Any new (as in not existed before) files will need to be listed in the appropriate sections in both the light and the dark `meson.build` files.

**Comment by m4u9** [comment]
@Appadeia ok but lets keep working on the the theme-split branch first to fix a few things I noticed:
- text of task manager has shadow
- thunar nav bar background doesn't match the rest of the window
- Thunar sidebar background might need to be lighter so that icons are more visible
- xfwm theme needs to be fixed

**Comment by sowelipililimute** [comment]
> * text of task manager has shadow

This is now fixed, now for the other three

**Comment by m4u9** [comment]
>     * Thunar sidebar background might need to be lighter so that icons are more visible

no need for this for now. I made a PR to elementary-xfce to change the music folder icon color so that it has a better contrast.

https://github.com/shimmerproject/elementary-xfce/pull/164

**Comment by m4u9** [comment]
OK now LGTM
I will go ahead and merge soon

thunar-light
thunar-dark

**Pull request merged**
